[project]
name = "streamlit-snowflake-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "snowflake-connector-python>=3.14.0",
    "snowflake-snowpark-python>=1.30.0",
    "streamlit>=1.44.0",
]
