# Change this file name to secrets.toml and adapt the values with your own

[connections.snowflake]
account = "<org>-<account>"
user = "<user>"
password = "<password>"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "BICING"
schema = "BICING_SCHEMA"